server:
    port: 8080
    error:
        include-exceptions: false
        include-stacktrace: never
        include-message: always
spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher